# Generated by Django 4.2.2 on 2023-07-31 21:19

import Fshare.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('background_color', models.CharField(default='white', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='subheader_images')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubHeader', to='Fshare.header')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=100, null=True, verbose_name='About')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(blank=True, default='profileimage/profile.png', null=True, upload_to='profileimage')),
                ('mode', models.CharField(default='white', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_path', models.CharField(blank=True, default='C:/Users/USER/Documents/WDP/Django/', max_length=10000, null=True)),
                ('name', models.CharField(max_length=10000)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='folder_cover_photos')),
                ('privacy', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('authorize', 'authorize')], default='public', max_length=20)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('info', models.TextField(blank=True, null=True, verbose_name='About Directory')),
                ('contributors', models.ManyToManyField(blank=True, related_name='our_folder', to='Fshare.profile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='Fshare.profile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folder', to='Fshare.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('file', models.FileField(default='file/empty.txt', upload_to=Fshare.models.upload_file)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('clone', models.BooleanField(default=False)),
                ('edit_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_file_edit', to='Fshare.profile')),
                ('edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_file', to='Fshare.file')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='Fshare.folder')),
            ],
        ),
    ]
