# Generated by Django 4.0.2 on 2022-11-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(model_name='file', name='clone', field=models.BooleanField(default=False), ), 
    ]
