# Generated by Django 4.2.2 on 2023-07-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='folder_like', to='Fshare.profile'),
        ),
    ]
