# Generated by Django 4.1 on 2022-11-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0002_cloneAdd'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='About Directory'),
        ),
    ]
