# Generated by Django 4.2.2 on 2023-08-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0002_folder_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
