# Generated by Django 4.2.2 on 2023-09-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0003_folder_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
