# Generated by Django 4.1.7 on 2023-04-29 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0003_folder_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('background_color', models.CharField(default='white', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='subheader_images')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubHeader', to='Fshare.header')),
            ],
        ),
    ]
