# Generated by Django 4.2.2 on 2023-09-27 11:58

import Fshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0004_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Fshare.models.upload_file),
        ),
    ]
