# Generated by Django 4.2.2 on 2023-06-20 15:00

import Fshare.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0004_header_subheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='file/empty.txt', storage=Fshare.models.select_storage, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profileimage/profile.png', null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/profileimage'), upload_to='profileimage'),
        ),
    ]
