# Generated by Django 4.2.2 on 2023-09-27 12:05

import Fshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0005_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='empty', upload_to=Fshare.models.upload_file),
        ),
    ]
