# Generated by Django 4.2.2 on 2023-09-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0007_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='size',
            field=models.IntegerField(default=26214400),
        ),
    ]
