# Generated by Django 4.2.2 on 2023-09-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0008_profile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_size',
            field=models.IntegerField(default=26214400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
