# Generated by Django 4.2.2 on 2023-11-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0010_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='title',
        ),
        migrations.AlterField(
            model_name='notify',
            name='body',
            field=models.CharField(max_length=100000),
        ),
    ]
