# Generated by Django 4.2.2 on 2023-11-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fshare', '0011_remove_notify_title_alter_notify_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='txt', max_length=100000),
        ),
    ]
